In [85]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [86]:
f = open("../datasets/chat_data.txt", "r", encoding="utf-8")
data = f.read()

In [87]:
print(data[:1000])  # Print the first 1000 characters of the chat data to get an overview

06/05/2026, 18:25 - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*
06/05/2026, 18:06 - Akshat Talwar USAR created group "ㅤ"
06/05/2026, 18:12 - Yash ShahiUsar added you
06/05/2026, 18:12 - Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab hona hai yeh
06/05/2026, 18:12 - Waqar AkhtarUsar: Agar saath hua toh Geetansh ko bhi kar le
06/05/2026, 18:12 - Yash ShahiUsar: Saath h
06/05/2026, 18:12 - Yash ShahiUsar: Phir jiya bhi h
06/05/2026, 18:14 - Akshat Talwar USAR: sir ka number hai?
06/05/2026, 18:14 - Himanshu USAR: +91 75032 88678
06/05/2026, 18:39 - Yash ShahiUsar: Sir se bhi baat huyi khrhe hoskta h kal mai aajau file le hi aana apni
06/05/2026, 18:39 - Yash ShahiUsar: 🙏🏻
06/05/2026, 19:09 - Ojus MathurUsar: Waah
06/05/2026, 19:09 - Ojus MathurUsar: Ye plan to khtm matlab
06/05/2026, 20:09 - Shashank USAR: Kya Krna hai yrr phir 😔
06/05/2026, 20:12 - Akshat Talwar USAR: <Media omitted>
06/05/2026, 20:18 - Yash Shahi

In [88]:
print(type(data))

<class 'str'>

In [89]:
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [90]:
import re
messages = re.split(pattern, data)[1:]
messages

['Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*\n',
 'Akshat Talwar USAR created group "ㅤ"\n',
 'Yash ShahiUsar added you\n',
 'Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab hona hai yeh\n',
 'Waqar AkhtarUsar: Agar saath hua toh Geetansh ko bhi kar le\n',
 'Yash ShahiUsar: Saath h\n',
 'Yash ShahiUsar: Phir jiya bhi h\n',
 'Akshat Talwar USAR: sir ka number hai?\n',
 'Himanshu USAR: +91 75032 88678\n',
 'Yash ShahiUsar: Sir se bhi baat huyi khrhe hoskta h kal mai aajau file le hi aana apni\n',
 'Yash ShahiUsar: 🙏🏻\n',
 'Ojus MathurUsar: Waah\n',
 'Ojus MathurUsar: Ye plan to khtm matlab\n',
 'Shashank USAR: Kya Krna hai yrr phir 😔\n',
 'Akshat Talwar USAR: <Media omitted>\n',
 'Yash ShahiUsar: Abe chinta mt kro shyd kaha tha usne\n',
 'Yash ShahiUsar: Stick to our plan\n',
 'Akshat Talwar USAR: APES TOGETHER STRONG\n',
 'Akshat Talwar USAR: hamare group ka naam leak nahi ho sakta\n',
 'Shashank USAR: "Sir yeh ____ ke bndo ne nakal ki"\n',
 'Ojus MathurUsar: bhai me to kahra hu 2-2 ke pair me karo \ncross validate karte rahenge \n\nand last me ek overview\n',
 'Ojus MathurUsar: 🤣🤣\n',
 'Yash ShahiUsar: Bdhiya h\n',
 'Akshat Talwar USAR: This message was deleted\n',
 'Yash ShahiUsar: Acha yrr\n',
 'Ojus MathurUsar: aree sahi me\n',
 'Yash ShahiUsar: Ab bss krdo\n',
 'Yash ShahiUsar: Ada hi padhlo\n',
 'Yash ShahiUsar: Aur gpt karlo cn gpt\n',
 'Shubham Shankar USAR: Hnn bhai ADA padho\n',
 'Yash ShahiUsar: @\u2068Shubham Shankar USAR\u2069 padhle CN bhi\n',
 'Ojus MathurUsar: ada ka time aaya ?\n',
 'Shubham Shankar USAR: Accha saale atul mera cartoon network krdega\n',
 '+91 78385 66006: YES\n',
 'Ojus MathurUsar: pata laga chutti karde\n',
 'Yash ShahiUsar: Nopes khrhe 9-10 apni class mein lunga\n',
 'Shubham Shankar USAR: Abe toh cn ka bhi toh yhi timing h\n',
 'Akshat Talwar USAR: a and b group?\n',
 'Ojus MathurUsar: wait what \n\ntab cn nhi h ?\n',
 'Yash ShahiUsar: 10-11 cn\n',
 'Ojus MathurUsar: aur ek sath?\n',
 'Yash ShahiUsar: Yes sir\n',
 'Akshat Talwar USAR: questions nikalwaye ada ke?\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Ojus MathurUsar: dm\n',
 '+91 78385 66006: allee thenkyuuuuuuu\n',
 'Yash ShahiUsar: B2 se baat cheet kro\n',
 'Shubham Shankar USAR: Iska front page aur index\n',
 'Yash ShahiUsar: Sab krke dedu tu kyu h phir ?\n',
 'Akshat Talwar USAR: daalu message support kardena\n',
 'Yash ShahiUsar: Abe ojus ne niklwaye toh the\n',
 'Akshat Talwar USAR: ohhh wait\n',
 'Yash ShahiUsar: Sorting techniques \nSaare Sorting ke time complexity \n\nLinear and binary search\nTime complexity \n\nWhat is 0/1 knapsack ( with time complexity)\nFractional knapsack and time complexity\n\nMinimum spanning tree\n\nEtc etc\n',
 'Yash ShahiUsar: Ye maximum puchrahe..\n\nKoi chance nahi lena to\n\nActivity selection , job sequencing problem, huffmann coding .. inke bhi complexity yaad karlena\n',
 'Ojus MathurUsar: msg padh  na\n',
 'Ojus MathurUsar: bheja hua h\n',
 'Yash ShahiUsar: Hnn vhi toh\n',
 'Akshat Talwar USAR: etc etc nikalwate hai\n',
 'Yash ShahiUsar: Okk\n',
 'Akshat Talwar USAR: unit 4 chhod du?\n',
 'Yash ShahiUsar: Bhai mera roll no. Bhi last ka h thoda bhot dekh jaaunga\n',
 'Yash ShahiUsar: Abhi toh phle 3 hi krlu bhot h\n',
 'Akshat Talwar USAR: 🤣🤣\n',
 'Yash ShahiUsar: Last mein aate aate teachers ko slow hona chahiye aur fast hojate h\n',
 'Yash ShahiUsar: Ki acha occams razor batao 🙏🏻\n',
 'Akshat Talwar USAR: sir mai leleti hu baaki bachcho ka viva <This message was edited>\n',
 'Yash ShahiUsar: Are thik h bhai\n',
 'Akshat Talwar USAR: aray mam aap 🥰\n',
 'Akshat Talwar USAR: *array\n',
 'Shashank USAR: Last rubin karp tk krra mai toh\n',
 'Shashank USAR: Class me bhi vhi tk hua hai\n',
 'Shashank USAR: Baaki puchne ko toh voh AVL trees se bhi puchre\n',
 'Akshat Talwar USAR: okie\n',
 "Shashank USAR: There's no end to their tomfoolery atp\n",
 'Shashank USAR: <Media omitted>\n',
 'Yash ShahiUsar: Wtf why AVL bro ?\n',
 'Akshat Talwar USAR: read next line\n',
 'Shashank USAR: Mauj msti me\n',
 'Shashank USAR: <Media omitted>\n',
 'Akshat Talwar USAR: <Media omitted>\n',
 'Yash ShahiUsar: /r\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Akshat Talwar USAR: \\n\n',
 'Akshat Talwar USAR: damnn 🤣🤣🤣\n',
 'Yash ShahiUsar: To enter in  next line\n',
 'Shashank USAR: If one has to attempt studying CN\n',
 'Shashank USAR: What would be the plan other than praying\n',
 'Waqar AkhtarUsar: Sirf 9-10 ke beech mei kitna viva le lega yeh atul\n',
 'Yash ShahiUsar: Yrr ye aalas ka kya kru\n',
 'Shashank USAR: <Media omitted>\n',
 'Waqar AkhtarUsar: Group A ka bhi Bach Raha hai\n',
 'Yash ShahiUsar: Bkl h khta raat tk krta hu confirm\n',
 'Akshat Talwar USAR: soja fir uth kar padh liyo\n',
 'Waqar AkhtarUsar: CN ka index tunne banaya nhi hai ya abhi pucha nhi sir se\n',
 'Waqar AkhtarUsar: ?\n',
 'Yash ShahiUsar: Bhai atp what will you study tell me there is no end to this syllabus <This message was edited>\n',
 'Yash ShahiUsar: Banaya nhi\n',
 'Yash ShahiUsar: Banana toh h hi\n',
 'Waqar AkhtarUsar: Bana le ya bta de dates\n',
 'Shashank USAR: Vhi toh bhai samjh hi ni aara literally no one has studied for this\n',
 'Akshat Talwar USAR: print karwaye file ya nahi\n',
 'Shashank USAR: <Media omitted>\n',
 'Waqar AkhtarUsar: Mai jaake print nikalwa laon\n',
 'Yash ShahiUsar: Dates ka dekhte h abhi rukjao sir\n',
 'Waqar AkhtarUsar: Ok\n',
 '+91 78385 66006: UFF YESS\n',
 'Yash ShahiUsar: Are yrr ek name page and index ke liye itna rona\n',
 'Waqar AkhtarUsar: At the end woh Time complexity hi puchega\n',
 'Yash ShahiUsar: Yaha bcho ne file ni banayi\n',
 'Yash ShahiUsar: Not ada sir\n',
 '+91 78385 66006: aur 9-10 to apni quiz hogi atul sir to baad me lenge na viva?\n',
 'Akshat Talwar USAR: cn\n',
 'Yash ShahiUsar: Yrr ada ka toh hojyega sab krlunga\n',
 'Yash ShahiUsar: Notes hi bhejdunga ek kaam kro b2 se saare q niklwao\n',
 'Akshat Talwar USAR: i am glad you have roll number in last\n',
 '+91 78385 66006: kya koi vyakti h jisne apni print out na nikalwayi ho?...\n',
 'Yash ShahiUsar: Me\n',
 'Akshat Talwar USAR: yess mee\n',
 'Yash ShahiUsar: Abe easy h ada yrr atlast sir apni marji se marks denge\n',
 '+91 78385 66006: meri le aaooo koiii saath me apnee\n',
 "Shashank USAR: Teri file ki sbne niklwali hogi abtk I'm sure\n",
 'Shashank USAR: <Media omitted>\n',
 'Yash ShahiUsar: 🙏🏻\n',
 'Akshat Talwar USAR: ada ka nahi kah raha vaise hi\ntera roll number agar shuru mei hota toh teachers ki expectation bad jaati\n',
 'Akshat Talwar USAR: *badh\n',
 'Waqar AkhtarUsar: Mai ja raha nikalwane\n',
 'Akshat Talwar USAR: meri nikalwa de\n',
 'Akshat Talwar USAR: kal dedunga paise\n',
 'Waqar AkhtarUsar: Bhej\n',
 'Akshat Talwar USAR: same pdf\n',
 'Akshat Talwar USAR: yash wala\n',
 'Waqar AkhtarUsar: Ok\n',
 'Akshat Talwar USAR: kitne page honge\n',
 'Shashank USAR: 42\n',
 'Waqar AkhtarUsar: Folder bhi lelu?\n',
 'Akshat Talwar USAR: kitne ka hoga\n',
 'Yash ShahiUsar: Bhai\n',
 'Waqar AkhtarUsar: ₹42\n',
 'Akshat Talwar USAR: folder\n',
 'Waqar AkhtarUsar: 10 ka folder\n',
 'Akshat Talwar USAR: haa lele\n',
 'Yash ShahiUsar: Mera bhi waqar folder rhne de vo h tu mera print niklwa le\n',
 'Yash ShahiUsar: Mai index and front banata\n',
 'Akshat Talwar USAR: mera folder + file\n',
 'Ojus MathurUsar: cn ka code kya h ?\n',
 'Ojus MathurUsar: subject code\n',
 'Yash ShahiUsar: Time table se dekhle\n',
 'Yash ShahiUsar: Lab ka\n',
 'Waqar AkhtarUsar: Kitne der mei bhejega ?\n',
 'Ojus MathurUsar: nhi h time table yaar\n',
 'Ojus MathurUsar: bata do koi\n',
 'Waqar AkhtarUsar: 10-15 min mei bhej de toh woh bhi nikalwa loon\n',
 'Akshat Talwar USAR: lol i use that colourful table\n',
 'Shubham Shankar USAR: ARM-258\n',
 'Akshat Talwar USAR: lord\n',
 'Yash ShahiUsar: 15-20 min de\n',
 'Waqar AkhtarUsar: Bhej\n',
 'Waqar AkhtarUsar: Mera aur Akshat ka bhi bana ke bhejiyo abb\n',
 'Waqar AkhtarUsar: @\u2068~Yashna Verma\u2069 tera bhi?\n',
 'Shubham Shankar USAR: Word file bhi bhej hi dio\n',
 'Yash ShahiUsar: Waiting for this message\n',
 'Shashank USAR: Pages ke dono side print krwa skte hain?\n',
 'Shashank USAR: <Media omitted>\n',
 'Shashank USAR: @\u2068all\u2069\n',
 'Shubham Shankar USAR: Bhai ig nikalwa skte kyuki vh file bss record ke liye lera h\n',
 'Shubham Shankar USAR: Uske marks nhi h\n',
 'Shashank USAR: Hain?\n',
 'Shashank USAR: Acha okay lol\n',
 'Shashank USAR: Niklwa lera phir\n',
 'Shubham Shankar USAR: Hnn\n',
 'Shubham Shankar USAR: Kal joh 40 marks ka test h full ussi ke mark lagnge\n',
 'Shubham Shankar USAR: Naa koi attendance naa file\n',
 'Shashank USAR: Abe yrr\n',
 'Shashank USAR: Kya bakwas hai ksm se\n',
 'Shashank USAR: External me bhi isi ke lgaenge\n',
 'Shubham Shankar USAR: Hnn\n',
 'Shubham Shankar USAR: Usne bola tha yhi pakda dunga external teacher ko\n',
 'Shashank USAR: Padhlo 1200 pages ki kitab baccho padh skte toh literally 3-4 din diye hain tumhe and uske saath voh 25 exp bhi krne hai\n',
 "Shashank USAR: I'm so done with this atp bhai this is so unfair\n",
 'Shashank USAR: <Media omitted>\n',
 'Shubham Shankar USAR: Ada padh le bhai chodd yeh sab\n',
 'Shashank USAR: Yeah vhi krra\n',
 'Shashank USAR: <Media omitted>\n',
 '+91 78385 66006: Mera bhii pleassee\n',
 'Waqar AkhtarUsar: Folder and file both ?\n',
 '+91 78385 66006: Yesss pleasee\n',
 '+91 78385 66006: Hn\n',
 'Waqar AkhtarUsar: Okay\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Yash ShahiUsar: waqar ye le print kra de fatafat\n',
 'Waqar AkhtarUsar: Waiting for this message\n',
 '+91 78385 66006: <Media omitted>\n',
 '+91 78385 66006: Pleasee ye bhi karwa Lena agar wahi ho to @\u2068Waqar AkhtarUsar\u2069\n',
 'Deepak Singh: <Media omitted>\n',
 'Arghyadeep USAR: Ham logo ka realistically ada ka viva hona possible hai kya?\n',
 '+91 78385 66006: Mera to shayad ho jaye tum log to baad me hi ho kaafi except ojus\n',
 'Yash ShahiUsar: bhai sir thode se bkl h kya\n',
 'Shubham Shankar USAR: Yeh kya bakchodi h\n',
 'Yash ShahiUsar: 25 min krdiya\n',
 'Shashank USAR: Abe\n',
 'Shashank USAR: BADHANE KO BOLA THA KM KR DIYA\n',
 'Shubham Shankar USAR: Yeh kon krra h 5 min mein test\n',
 '+91 78385 66006: 😭🤣\n',
 'Shubham Shankar USAR: Thoda nhi purra hi h\n',
 'Shashank USAR: Aasaan hoga phir ig\n',
 'Yash ShahiUsar: naah\n',
 'Shashank USAR: Bro wants ki ek subject me toh back lge hi sbki🤭\n',
 'Shashank USAR: Bhai if we get lucky and ordered aaya sb\n',
 'Shashank USAR: Toh ready rehna\n',
 'Akshat Talwar USAR: questions paper can be solved in just 5 minutes\n',
 'Akshat Talwar USAR: isko ghar mei koi serious nahi leta\n',
 '+91 78385 66006: Easy hoga SIR KE LIYE\n',
 'Akshat Talwar USAR: isliye\n',
 'Akshat Talwar USAR: bachcho se compete karta hai\n',
 'Shashank USAR: Kuch ho gya hoga yrr\n',
 'Shashank USAR: Inke Ghar me\n',
 'Ojus MathurUsar: bhai seedha hi maar dalo dono milkar \naise kyu pareshan karre h\n',
 '~\u202fYashna Verma changed the group name from "ㅤ" to "Some name to the group"\n',
 'Shashank USAR: Irrational behaviour\n',
 'Shashank USAR: Bullying speedrun\n',
 'Ojus MathurUsar: Bhyii mera laptop pagal ho gya h \n\nEk site par tabse khudko insaan batane me laga hu\nRobot detect karra h\n',
 'Ojus MathurUsar: 😭😭😭\n',
 'Ojus MathurUsar: Alag hi laga pada h\n',
 'Shashank USAR: Bhai Mera toh gayming hai 25 min toh usko bina charger ke tab switch krne me hi lgne wale hain\n',
 'Shashank USAR: <Media omitted>\n',
 'Akshat Talwar USAR: well can it actually handle games?\n',
 'Akshat Talwar USAR: just asking\n',
 'Shashank USAR: Yes\n',
 'Shashank USAR: But usually a bit slow without charger\n',
 'Shashank USAR: <Media omitted>\n',
 'Yash ShahiUsar: bhai mobile app dev ye pdhayega toh lggye apne ?\n',
 'Akshat Talwar USAR: like what max game\n',
 'Akshat Talwar USAR: yeh padhayega \npls no\n',
 'Shashank USAR: God of war Ragnarok 100+ ish fps\n',
 'Shashank USAR: <Media omitted>\n',
 'Shashank USAR: With charger\n',
 'Ojus MathurUsar: kon?\n',
 'Shashank USAR: Without 60 aate\n',
 'Yash ShahiUsar: abhishek\n',
 'Shubham Shankar USAR: Nhi maine pucha tha isse mnna kr dia tha isne\n',
 'Shubham Shankar USAR: Vh nhi padhayega\n',
 'Yash ShahiUsar: bdhiya chlo\n',
 'Akshat Talwar USAR: damnnn\n',
 'Shubham Shankar USAR: Abe pce mein kya krna h  abb\n',
 'Ojus MathurUsar: bhaii nhi ye nhi hona chahiye\n',
 "Shashank USAR: 8tk ka time hai let's focus on more important matters now\n",
 'Yash ShahiUsar: lets decide bro\n',
 'Ojus MathurUsar: soft\n',
 'Shashank USAR: For now*\n',
 'Shashank USAR: <Media omitted>\n',
 'Ojus MathurUsar: computing\n',
 'Yash ShahiUsar: guys cn ka krlo koi toh agar cheat na hua toh ?\n',
 'Ojus MathurUsar: kiska ada accha h wo karo\n',
 'Shubham Shankar USAR: Yash\n',
 'Yash ShahiUsar: abee\n',
 'Yash ShahiUsar: cn hona chahiye na acha\n',
 'Yash ShahiUsar: ada se mai kya krlunga\n',
 'Yash ShahiUsar: mujhe paper pata ho cn ka toh krlunga\n',
 'Shashank USAR: Mujhe agr aata bhi hoga toh 25 minutes me na hora paper\n',
 'Shubham Shankar USAR: Tu cn padhega na fir ada toh ho gya tera\n',
 'Yash ShahiUsar: vrna merse dur hi rkho isse\n',
 'Yash ShahiUsar: start toh krne de\n',
 'Yash ShahiUsar: ye bhi h 25 min mein toh cheating se hi hoskta h\n',
 'Shashank USAR: Vohi\n',
 'Shubham Shankar USAR: Toh questions batt kr hi hoga <This message was edited>\n',
 'Shubham Shankar USAR: Apna part krke pass on aage\n',
 'Yash ShahiUsar: abe baat kr bhi kaise hoga ye sir pr khda rhega toh\n',
 'Shubham Shankar USAR: Abe bhott log h class mein\n',
 'Ojus MathurUsar: bhaii metro me quick overview kar lunga me chalo\n',
 'Shubham Shankar USAR: Humare pr toh nhi hi hoga itna\n',
 'Shashank USAR: Upper cut to the chin\n',
 'Shashank USAR: <Media omitted>\n',
 'Ojus MathurUsar: aise hi karlo sab overview taaki cross check ho sake\n',
 'Shashank USAR: Abe yrr itni ambiguity hai ek toh\n',
 'Yash ShahiUsar: crosws check ki aisi taisi\n',
 'Ojus MathurUsar: notes ke naam par copy aur print change karo yaar\n',
 'Shashank USAR: Kuch pta hi ni ki yeh aaenge ya nhi\n',
 'Yash ShahiUsar: bhai jldi jldi krna saare speedrun\n',
 'Shubham Shankar USAR: Abe theory wle toh aram se ho jaynge options ke saath toh\n',
 'Shashank USAR: This message was deleted\n',
 'Shashank USAR: Yeah\n',
 'Waqar AkhtarUsar: Bana liya tha maine tera\n',
 'Shashank USAR: No lmao???\n',
 'Waqar AkhtarUsar: Hogaya abb sabka\n',
 'Ojus MathurUsar: sprint\n',
 '+91 78385 66006: THANKYUUUU\n',
 'Yash ShahiUsar: Bhai bss 30 no. Ka krwa dena bss aage ka kuch nhi chahiye\n',
 'Yash ShahiUsar: Aur vo +5 wali baat kaha gyi sir ki\n',
 'Yash ShahiUsar: 😭\n',
 'Shashank USAR: It takes atleast like 40 seconds to read and solve a question bhai kaise krega saare iss approach se\n',
 '+91 78385 66006: vo meethi goli thi neesa\n',
 'Shubham Shankar USAR: Hnn vh bhi toh h\n',
 'Shubham Shankar USAR: Kal ayega toh bolunga usse\n',
 'Yash ShahiUsar: Acha\n',
 'Shubham Shankar USAR: Baaki dega yah ni vh toh uske upr h\n',
 'Shubham Shankar USAR: Vese hi time kamm kr dia h\n',
 'Yash ShahiUsar: Ab ada padhna start krta hu 10 se\n',
 '+91 78385 66006: abhi tak cn karra tha\n',
 'Yash ShahiUsar: Cn subah dekhlunga notes lekar aaunga open book h na\n',
 'Yash ShahiUsar: 🗣🗣\n',
 'Yash ShahiUsar: Nahi aalas\n',
 '+91 78385 66006: us moment\n',
 '+91 78385 66006: mai 1.5 hours soyi\n',
 '+91 78385 66006: aur uthke bhi nhi uthi\n',
 'Yash ShahiUsar: Mai soya bhi toh nhi\n',
 'Yash ShahiUsar: Ab neend aarhi h\n',
 '+91 78385 66006: sone me bhi aalas lol\n',
 'Yash ShahiUsar: Aalas insan ko kha jaata h\n',
 '+91 78385 66006: ye tar aapko bahut beemar bana sakta h\n',
 'Ojus MathurUsar: mera to 1 hr me sone ka time h \n\nkaam khtm mera to\n',
 '+91 78385 66006: alle\n',
 'Yash ShahiUsar: Kitna padha ada\n',
 'Ojus MathurUsar: alle kya subha hi uthke karna padega sab\n',
 'Yash ShahiUsar: Yrr ada is all about time complexity af everything in all cases\n',
 'Yash ShahiUsar: 🗣🗣\n',
 'Ojus MathurUsar: ye to subha shuru ke baccho se judge karke nhi padhna tha?\n',
 'Ojus MathurUsar: 🤣🤣\n',
 'Ojus MathurUsar: overview hi hoga bas dono ka\n',
 'Ojus MathurUsar: karo sab aaram se\n',
 'Ojus MathurUsar: itna tension kyu lena\n',
 'Yash ShahiUsar: Hnn ye bhi h\n',
 'Yash ShahiUsar: agent bana rhe ho toh bna lo\n',
 'Yash ShahiUsar: @\u2068Akshat Talwar USAR\u2069 @\u2068Ojus MathurUsar\u2069\n',
 'Ojus MathurUsar: book ki pdf do pahle\n',
 'Ojus MathurUsar: usko padhne ke liye to dekhu\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Yash ShahiUsar: Book ek ye h ek foruzan derha\n',
 'Yash ShahiUsar: <Media omitted>\n',
 'Yash ShahiUsar: Aur file daaldiyo practical sir ki jo h classroom pr\n',
 'Ojus MathurUsar: ok\n',
 'Waqar AkhtarUsar: Ada ka confirm hua?\n',
 'Waqar AkhtarUsar: Cause yeh insaan thrusday 9:40 par chala jata hai\n',
 'Yash ShahiUsar: Sir abhi delhi pahuche hai\n',
 'Yash ShahiUsar: Ab CN ka padhte h\n',
 'Yash ShahiUsar: 🗣🗣\n',
 'Yash ShahiUsar: Ada toh shift hogya\n',
 'Shashank USAR: Abe yrr ab Friday bhi aao 💔\n',
 'Yash ShahiUsar: Bhai kya aap prefer krte 5 baje viva dena when you are free at 11\n',
 'Shashank USAR: Hell no\n',
 'Shashank USAR: Friday hi theekh hai\n',
 'Shashank USAR: <Media omitted>\n',
 'Yash ShahiUsar: Bss\n',
 'Yash ShahiUsar: That is choice for me to make i did that\n',
 '+91 78385 66006: EXACTLY\n',
 'Yash ShahiUsar: Ki fri dedo\n',
 '+91 78385 66006: good choice\n',
 'Shashank USAR: Shi kiya shi kiya\n',
 'Akshat Talwar USAR: kal ka kya scene hai\n',
 'Akshat Talwar USAR: @\u2068Yash ShahiUsar\u2069\n',
 'Akshat Talwar USAR: cn padh kar aau?\n',
 'Akshat Talwar USAR: koi task dedo\n',
 'Yash ShahiUsar: Bhai 9-10 adaka viva dena h tujhe ?\n',
 'Akshat Talwar USAR: ada toh cancel na\n',
 'Yash ShahiUsar: Guys if we have time lets divide chapters among ourselves\n',
 'Yash ShahiUsar: Option h kal deskte ho if 9-10 dena ho toh\n',
 'Shashank USAR: Sir aare kya kl CN wale?\n',
 'Yash ShahiUsar: Itni subah jaane ka mnn ni hota\n',
 'Shashank USAR: Tu toh kehra tha shayad hai\n',
 'Akshat Talwar USAR: ??\n',
 'Yash ShahiUsar: Not sure aaskte h\n',
 'Akshat Talwar USAR: no no\n',
 'Shashank USAR: Hume toh mna krre the\n',
 'Shashank USAR: Ki mai nhi hunga anupam sir lenge blah blah\n',
 'Shashank USAR: <Media omitted>\n',
 'Shashank USAR: Shit yrr dikkat ho jaegi phir toh\n',
 'Akshat Talwar USAR: network layer se dedo mujhe chapters\n',
 'Yash ShahiUsar: @\u2068all\u2069 batao chapters divide krle ?\n',
 'Shashank USAR: Dikkat ho jaaegi agr uss chapter se ek bnda krke aaya aur use na aaya toh sbka jaaega voh\n',
 'Akshat Talwar USAR: yes sir\n',
 'Akshat Talwar USAR: ada ka dega yash?\n',
 'Akshat Talwar USAR: agree +1\n',
 'Akshat Talwar USAR: i trust gpt more than myself\n',
 'Shashank USAR: Baaki bta do sb kya decide krre\n',
 'Akshat Talwar USAR: 10 log hai group mei\n8 maan kar chalte hai\ndo do ka duo bana lo\n',
 'Akshat Talwar USAR: sab 10 question bhej dena <This message was edited>\n',
 'Akshat Talwar USAR: and duo mei answers cross validate ho jayenge\n',
 'Akshat Talwar USAR: and we can also make it less complex \n\nsaare Hi bhej dena ek saath <This message was edited>\n',
 'Akshat Talwar USAR: discuss kar lenge\n',
 'Akshat Talwar USAR: discard this idea\n',
 'Yash ShahiUsar: are gpt rkho i am saying ki if sir ne naa krne diya cheat toh\n',
 'Yash ShahiUsar: yrr subah aane ka mnn nhi + questions aajayenge aur\n',
 'Yash ShahiUsar: fri hi aajyenge\n',
 'Yash ShahiUsar: @\u2068all\u2069 confirm kro ada friday ko and kuch nhi pdhu na phir CN\n',
 'Yash ShahiUsar: toh sone jaau\n',
 'Akshat Talwar USAR: sir ne puri book boli hai?\n',
 'Akshat Talwar USAR: agar padhna hai toh kya padhu\n',
 'Yash ShahiUsar: hnn cisco packet tracer bhi bhai\n',
 'Ojus MathurUsar: Kal bas CN h na ??\n',
 'Ojus MathurUsar: 10 se\n',
 'Yash ShahiUsar: tu dega ada vhi pucha h 9-10 and 5 ka slot h\n',
 'Ojus MathurUsar: Dere ho tum log?\n',

In [91]:
# extracting dates from the data
dates = re.findall(pattern,data)
dates

['06/05/2026, 18:25 - ',
 '06/05/2026, 18:06 - ',
 '06/05/2026, 18:12 - ',
 '06/05/2026, 18:12 - ',
 '06/05/2026, 18:12 - ',
 '06/05/2026, 18:12 - ',
 '06/05/2026, 18:12 - ',
 '06/05/2026, 18:14 - ',
 '06/05/2026, 18:14 - ',
 '06/05/2026, 18:39 - ',
 '06/05/2026, 18:39 - ',
 '06/05/2026, 19:09 - ',
 '06/05/2026, 19:09 - ',
 '06/05/2026, 20:09 - ',
 '06/05/2026, 20:12 - ',
 '06/05/2026, 20:18 - ',
 '06/05/2026, 20:18 - ',
 '06/05/2026, 20:19 - ',
 '06/05/2026, 20:19 - ',
 '06/05/2026, 20:20 - ',
 '06/05/2026, 20:20 - ',
 '06/05/2026, 20:20 - ',
 '06/05/2026, 20:20 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:21 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:22 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:23 - ',
 '06/05/2026, 20:24 - ',
 '06/05/2026, 20:24 - ',
 '06/05/2026, 20:24 - ',
 '06/05/2026, 20:24 - ',
 '06/05/2026, 20:24 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:25 - ',
 '06/05/2026, 20:26 - ',
 '06/05/2026, 20:26 - ',
 '06/05/2026, 20:26 - ',
 '06/05/2026, 20:27 - ',
 '06/05/2026, 20:28 - ',
 '06/05/2026, 20:28 - ',
 '06/05/2026, 20:28 - ',
 '06/05/2026, 20:30 - ',
 '06/05/2026, 20:30 - ',
 '06/05/2026, 20:30 - ',
 '06/05/2026, 20:30 - ',
 '06/05/2026, 20:30 - ',
 '06/05/2026, 20:30 - ',
 '06/05/2026, 20:31 - ',
 '06/05/2026, 20:31 - ',
 '06/05/2026, 20:32 - ',
 '06/05/2026, 20:32 - ',
 '06/05/2026, 20:32 - ',
 '06/05/2026, 20:33 - ',
 '06/05/2026, 20:34 - ',
 '06/05/2026, 20:34 - ',
 '06/05/2026, 20:34 - ',
 '06/05/2026, 20:34 - ',
 '06/05/2026, 20:34 - ',
 '06/05/2026, 20:34 - ',
 '06/05/2026, 20:34 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:35 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:36 - ',
 '06/05/2026, 20:37 - ',
 '06/05/2026, 20:37 - ',
 '06/05/2026, 20:37 - ',
 '06/05/2026, 20:37 - ',
 '06/05/2026, 20:37 - ',
 '06/05/2026, 20:37 - ',
 '06/05/2026, 20:37 - ',
 '06/05/2026, 20:38 - ',
 '06/05/2026, 20:38 - ',
 '06/05/2026, 20:38 - ',
 '06/05/2026, 20:38 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:39 - ',
 '06/05/2026, 20:40 - ',
 '06/05/2026, 20:40 - ',
 '06/05/2026, 20:40 - ',
 '06/05/2026, 20:40 - ',
 '06/05/2026, 20:40 - ',
 '06/05/2026, 20:40 - ',
 '06/05/2026, 20:40 - ',
 '06/05/2026, 20:41 - ',
 '06/05/2026, 20:41 - ',
 '06/05/2026, 20:41 - ',
 '06/05/2026, 20:41 - ',
 '06/05/2026, 20:41 - ',
 '06/05/2026, 20:41 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:42 - ',
 '06/05/2026, 20:43 - ',
 '06/05/2026, 20:43 - ',
 '06/05/2026, 20:43 - ',
 '06/05/2026, 20:43 - ',
 '06/05/2026, 20:43 - ',
 '06/05/2026, 20:43 - ',
 '06/05/2026, 20:44 - ',
 '06/05/2026, 20:44 - ',
 '06/05/2026, 20:44 - ',
 '06/05/2026, 20:44 - ',
 '06/05/2026, 20:44 - ',
 '06/05/2026, 20:45 - ',
 '06/05/2026, 20:48 - ',
 '06/05/2026, 20:49 - ',
 '06/05/2026, 20:49 - ',
 '06/05/2026, 20:50 - ',
 '06/05/2026, 20:50 - ',
 '06/05/2026, 20:50 - ',
 '06/05/2026, 20:51 - ',
 '06/05/2026, 20:51 - ',
 '06/05/2026, 20:51 - ',
 '06/05/2026, 20:51 - ',
 '06/05/2026, 20:51 - ',
 '06/05/2026, 20:52 - ',
 '06/05/2026, 20:53 - ',
 '06/05/2026, 20:53 - ',
 '06/05/2026, 20:54 - ',
 '06/05/2026, 20:54 - ',
 '06/05/2026, 20:54 - ',
 '06/05/2026, 20:54 - ',
 '06/05/2026, 20:55 - ',
 '06/05/2026, 20:55 - ',
 '06/05/2026, 20:55 - ',
 '06/05/2026, 20:55 - ',
 '06/05/2026, 20:55 - ',
 '06/05/2026, 21:05 - ',
 '06/05/2026, 21:05 - ',
 '06/05/2026, 21:05 - ',
 '06/05/2026, 21:05 - ',
 '06/05/2026, 21:05 - ',
 '06/05/2026, 21:11 - ',
 '06/05/2026, 21:11 - ',
 '06/05/2026, 21:12 - ',
 '06/05/2026, 21:12 - ',
 '06/05/2026, 21:12 - ',
 '06/05/2026, 21:13 - ',
 '06/05/2026, 21:16 - ',
 '06/05/2026, 21:17 - ',
 '06/05/2026, 21:18 - ',
 '06/05/2026, 21:19 - ',
 '06/05/2026, 21:21 - ',
 '06/05/2026, 21:22 - ',
 '06/05/2026, 21:22 - ',
 '06/05/2026, 21:22 - ',
 '06/05/2026, 21:22 - ',
 '06/05/2026, 21:22 - ',
 '06/05/2026, 21:22 - ',
 '06/05/2026, 21:23 - ',
 '06/05/2026, 21:23 - ',
 '06/05/2026, 21:23 - ',
 '06/05/2026, 21:23 - ',
 '06/05/2026, 21:23 - ',
 '06/05/2026, 21:24 - ',
 '06/05/2026, 21:24 - ',
 '06/05/2026, 21:24 - ',
 '06/05/2026, 21:24 - ',
 '06/05/2026, 21:24 - ',
 '06/05/2026, 21:24 - ',
 '06/05/2026, 21:24 - ',
 '06/05/2026, 21:25 - ',
 '06/05/2026, 21:25 - ',
 '06/05/2026, 21:25 - ',
 '06/05/2026, 21:25 - ',
 '06/05/2026, 21:25 - ',
 '06/05/2026, 21:26 - ',
 '06/05/2026, 21:26 - ',
 '06/05/2026, 21:26 - ',
 '06/05/2026, 21:27 - ',
 '06/05/2026, 21:27 - ',
 '06/05/2026, 21:27 - ',
 '06/05/2026, 21:28 - ',
 '06/05/2026, 21:29 - ',
 '06/05/2026, 21:29 - ',
 '06/05/2026, 21:29 - ',
 '06/05/2026, 21:29 - ',
 '06/05/2026, 21:30 - ',
 '06/05/2026, 21:30 - ',
 '06/05/2026, 21:30 - ',
 '06/05/2026, 21:30 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:31 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:32 - ',
 '06/05/2026, 21:38 - ',
 '06/05/2026, 21:39 - ',
 '06/05/2026, 21:39 - ',
 '06/05/2026, 21:39 - ',
 '06/05/2026, 21:39 - ',
 '06/05/2026, 21:39 - ',
 '06/05/2026, 21:40 - ',
 '06/05/2026, 21:40 - ',
 '06/05/2026, 21:40 - ',
 '06/05/2026, 21:40 - ',
 '06/05/2026, 21:40 - ',
 '06/05/2026, 21:40 - ',
 '06/05/2026, 21:41 - ',
 '06/05/2026, 21:41 - ',
 '06/05/2026, 21:42 - ',
 '06/05/2026, 21:42 - ',
 '06/05/2026, 21:43 - ',
 '06/05/2026, 21:43 - ',
 '06/05/2026, 21:43 - ',
 '06/05/2026, 21:44 - ',
 '06/05/2026, 21:44 - ',
 '06/05/2026, 21:44 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:45 - ',
 '06/05/2026, 21:46 - ',
 '06/05/2026, 21:46 - ',
 '06/05/2026, 21:46 - ',
 '06/05/2026, 21:46 - ',
 '06/05/2026, 21:46 - ',
 '06/05/2026, 21:47 - ',
 '06/05/2026, 21:47 - ',
 '06/05/2026, 21:47 - ',
 '06/05/2026, 21:47 - ',
 '06/05/2026, 21:47 - ',
 '06/05/2026, 21:47 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:48 - ',
 '06/05/2026, 21:49 - ',
 '06/05/2026, 21:49 - ',
 '06/05/2026, 21:49 - ',
 '06/05/2026, 21:50 - ',
 '06/05/2026, 21:50 - ',
 '06/05/2026, 21:50 - ',
 '06/05/2026, 21:50 - ',
 '06/05/2026, 21:51 - ',
 '06/05/2026, 21:51 - ',
 '06/05/2026, 21:51 - ',
 '06/05/2026, 21:51 - ',
 '06/05/2026, 21:51 - ',
 '06/05/2026, 21:55 - ',
 '06/05/2026, 22:02 - ',
 '06/05/2026, 22:07 - ',
 '06/05/2026, 22:08 - ',
 '06/05/2026, 22:08 - ',
 '06/05/2026, 22:09 - ',
 '06/05/2026, 22:09 - ',
 '06/05/2026, 22:09 - ',
 '06/05/2026, 22:10 - ',
 '06/05/2026, 22:11 - ',
 '06/05/2026, 22:11 - ',
 '06/05/2026, 22:11 - ',
 '06/05/2026, 22:12 - ',
 '06/05/2026, 22:18 - ',
 '06/05/2026, 22:18 - ',
 '06/05/2026, 22:18 - ',
 '06/05/2026, 22:19 - ',
 '06/05/2026, 22:20 - ',
 '06/05/2026, 22:20 - ',
 '06/05/2026, 22:20 - ',
 '06/05/2026, 22:20 - ',
 '06/05/2026, 22:20 - ',
 '06/05/2026, 22:21 - ',
 '06/05/2026, 22:21 - ',
 '06/05/2026, 22:21 - ',
 '06/05/2026, 22:21 - ',
 '06/05/2026, 22:21 - ',
 '06/05/2026, 22:30 - ',
 '06/05/2026, 22:30 - ',
 '06/05/2026, 22:31 - ',
 '06/05/2026, 22:31 - ',
 '06/05/2026, 22:31 - ',
 '06/05/2026, 22:31 - ',
 '06/05/2026, 22:31 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:32 - ',
 '06/05/2026, 22:33 - ',
 '06/05/2026, 22:33 - ',
 '06/05/2026, 22:33 - ',
 '06/05/2026, 22:33 - ',
 '06/05/2026, 22:33 - ',
 '06/05/2026, 22:34 - ',
 '06/05/2026, 22:34 - ',
 '06/05/2026, 22:34 - ',
 '06/05/2026, 22:35 - ',
 '06/05/2026, 22:35 - ',
 '06/05/2026, 22:36 - ',
 '06/05/2026, 22:36 - ',
 '06/05/2026, 22:36 - ',
 '06/05/2026, 22:37 - ',
 '06/05/2026, 22:38 - ',
 '06/05/2026, 22:39 - ',
 '06/05/2026, 22:39 - ',
 '06/05/2026, 22:46 - ',
 '06/05/2026, 22:46 - ',
 '06/05/2026, 22:47 - ',
 '06/05/2026, 22:47 - ',
 '06/05/2026, 22:47 - ',
 '06/05/2026, 22:48 - ',
 '06/05/2026, 22:48 - ',
 '06/05/2026, 22:48 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:49 - ',
 '06/05/2026, 22:50 - ',
 '06/05/2026, 22:50 - ',
 '06/05/2026, 22:50 - ',
 '06/05/2026, 22:51 - ',
 '06/05/2026, 22:51 - ',
 '06/05/2026, 22:51 - ',
 '06/05/2026, 22:51 - ',
 '06/05/2026, 22:51 - ',
 '06/05/2026, 22:51 - ',
 '06/05/2026, 22:51 - ',
 '06/05/2026, 22:52 - ',
 '06/05/2026, 22:52 - ',
 '06/05/2026, 22:52 - ',
 '06/05/2026, 22:52 - ',
 '06/05/2026, 22:53 - ',
 '06/05/2026, 22:53 - ',
 '06/05/2026, 22:53 - ',
 '06/05/2026, 22:54 - ',
 '06/05/2026, 22:54 - ',
 '06/05/2026, 22:54 - ',
 '06/05/2026, 22:55 - ',
 '06/05/2026, 22:55 - ',
 '06/05/2026, 22:55 - ',
 '06/05/2026, 22:55 - ',
 '06/05/2026, 22:55 - ',
 '06/05/2026, 22:55 - ',
 '06/05/2026, 22:55 - ',
 '06/05/2026, 22:56 - ',
 '06/05/2026, 22:56 - ',
 '06/05/2026, 22:56 - ',
 '06/05/2026, 22:56 - ',
 '06/05/2026, 22:56 - ',
 '06/05/2026, 22:56 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:57 - ',
 '06/05/2026, 22:58 - ',
 '06/05/2026, 22:58 - ',
 '06/05/2026, 22:58 - ',
 '06/05/2026, 22:58 - ',
 '06/05/2026, 22:58 - ',
 '06/05/2026, 22:58 - ',
 '06/05/2026, 22:59 - ',
 '06/05/2026, 22:59 - ',
 '06/05/2026, 22:59 - ',
 '06/05/2026, 22:59 - ',
 '06/05/2026, 22:59 - ',
 '06/05/2026, 22:59 - ',
 '06/05/2026, 22:59 - ',
 '06/05/2026, 23:01 - ',
 '06/05/2026, 23:01 - ',
 '06/05/2026, 23:02 - ',
 '06/05/2026, 23:02 - ',
 '06/05/2026, 23:02 - ',
 '06/05/2026, 23:03 - ',
 '06/05/2026, 23:03 - ',
 '06/05/2026, 23:03 - ',
 '06/05/2026, 23:03 - ',
 '06/05/2026, 23:03 - ',
 '06/05/2026, 23:04 - ',
 '06/05/2026, 23:04 - ',
 '06/05/2026, 23:04 - ',
 '06/05/2026, 23:06 - ',
 '06/05/2026, 23:06 - ',
 '06/05/2026, 23:06 - ',
 '06/05/2026, 23:06 - ',
 '06/05/2026, 23:06 - ',
 '06/05/2026, 23:06 - ',
 '06/05/2026, 23:07 - ',
 '06/05/2026, 23:07 - ',
 '06/05/2026, 23:08 - ',
 '06/05/2026, 23:08 - ',
 '06/05/2026, 23:09 - ',
 '06/05/2026, 23:09 - ',
 '06/05/2026, 23:09 - ',
 '06/05/2026, 23:09 - ',
 '06/05/2026, 23:10 - ',
 '06/05/2026, 23:10 - ',
 '06/05/2026, 23:11 - ',
 '06/05/2026, 23:11 - ',
 '06/05/2026, 23:15 - ',
 '06/05/2026, 23:15 - ',
 '06/05/2026, 23:15 - ',
 '06/05/2026, 23:16 - ',
 '06/05/2026, 23:16 - ',
 '06/05/2026, 23:17 - ',
 '06/05/2026, 23:17 - ',
 '06/05/2026, 23:17 - ',
 '06/05/2026, 23:17 - ',
 '06/05/2026, 23:19 - ',
 '06/05/2026, 23:27 - ',
 '06/05/2026, 23:27 - ',
 '07/05/2026, 07:51 - ',
 '07/05/2026, 07:51 - ',
 '07/05/2026, 07:51 - ',
 '07/05/2026, 07:52 - ',
 '07/05/2026, 07:52 - ',
 '07/05/2026, 07:58 - ',
 '07/05/2026, 08:01 - ',
 '07/05/2026, 08:01 - ',
 '07/05/2026, 08:02 - ',
 '07/05/2026, 08:05 - ',
 '07/05/2026, 08:07 - ',
 '07/05/2026, 08:07 - ',
 '07/05/2026, 08:09 - ',
 '07/05/2026, 08:09 - ',
 '07/05/2026, 08:09 - ',
 '07/05/2026, 08:10 - ',
 '07/05/2026, 08:10 - ',
 '07/05/2026, 08:10 - ',
 '07/05/2026, 08:10 - ',
 '07/05/2026, 08:10 - ',
 '07/05/2026, 08:10 - ',
 '07/05/2026, 08:10 - ',
 '07/05/2026, 08:12 - ',
 '07/05/2026, 08:13 - ',
 '07/05/2026, 08:14 - ',
 '07/05/2026, 08:14 - ',
 '07/05/2026, 08:14 - ',
 '07/05/2026, 08:16 - ',
 '07/05/2026, 08:16 - ',
 '07/05/2026, 08:16 - ',
 '07/05/2026, 08:16 - ',
 '07/05/2026, 08:16 - ',
 '07/05/2026, 08:17 - ',
 '07/05/2026, 08:17 - ',
 '07/05/2026, 08:17 - ',
 '07/05/2026, 08:17 - ',
 '07/05/2026, 08:17 - ',
 '07/05/2026, 08:17 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:18 - ',
 '07/05/2026, 08:19 - ',
 '07/05/2026, 08:19 - ',
 '07/05/2026, 08:19 - ',
 '07/05/2026, 08:19 - ',
 '07/05/2026, 08:20 - ',
 '07/05/2026, 08:20 - ',
 '07/05/2026, 08:20 - ',
 '07/05/2026, 08:20 - ',
 '07/05/2026, 08:20 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:21 - ',
 '07/05/2026, 08:22 - ',
 '07/05/2026, 08:22 - ',
 '07/05/2026, 08:22 - ',
 '07/05/2026, 08:22 - ',
 '07/05/2026, 08:24 - ',
 '07/05/2026, 08:24 - ',
 '07/05/2026, 08:24 - ',
 '07/05/2026, 08:24 - ',
 '07/05/2026, 08:27 - ',
 '07/05/2026, 08:28 - ',
 '07/05/2026, 08:29 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:45 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:46 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:47 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:48 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:49 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:50 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:51 - ',
 '07/05/2026, 08:52 - ',
 '07/05/2026, 08:52 - ',
 '07/05/2026, 08:52 - ',
 '07/05/2026, 08:52 - ',
 '07/05/2026, 08:52 - ',
 '07/05/2026, 08:53 - ',
 '07/05/2026, 08:53 - ',
 '07/05/2026, 08:53 - ',
 '07/05/2026, 08:53 - ',
 '07/05/2026, 08:54 - ',
 '07/05/2026, 08:54 - ',
 '07/05/2026, 08:54 - ',
 '07/05/2026, 08:54 - ',
 '07/05/2026, 08:54 - ',
 '07/05/2026, 08:54 - ',
 '07/05/2026, 08:55 - ',
 '07/05/2026, 08:55 - ',
 '07/05/2026, 08:55 - ',
 '07/05/2026, 08:55 - ',
 '07/05/2026, 08:55 - ',
 '07/05/2026, 08:55 - ',
 '07/05/2026, 08:56 - ',
 '07/05/2026, 08:56 - ',
 '07/05/2026, 08:56 - ',
 '07/05/2026, 08:56 - ',
 '07/05/2026, 08:57 - ',
 '07/05/2026, 08:57 - ',
 '07/05/2026, 08:57 - ',
 '07/05/2026, 08:57 - ',
 '07/05/2026, 08:57 - ',
 '07/05/2026, 08:58 - ',
 '07/05/2026, 08:58 - ',
 '07/05/2026, 08:58 - ',
 '07/05/2026, 08:58 - ',
 '07/05/2026, 08:58 - ',
 '07/05/2026, 08:59 - ',
 '07/05/2026, 08:59 - ',
 '07/05/2026, 08:59 - ',
 '07/05/2026, 08:59 - ',
 '07/05/2026, 08:59 - ',
 '07/05/2026, 09:00 - ',
 '07/05/2026, 09:00 - ',
 '07/05/2026, 09:00 - ',
 '07/05/2026, 09:00 - ',
 '07/05/2026, 09:00 - ',
 '07/05/2026, 09:03 - ',
 '07/05/2026, 09:03 - ',
 '07/05/2026, 09:03 - ',
 '07/05/2026, 09:03 - ',
 '07/05/2026, 09:04 - ',
 '07/05/2026, 09:04 - ',
 '07/05/2026, 09:04 - ',
 '07/05/2026, 09:04 - ',
 '07/05/2026, 09:04 - ',
 '07/05/2026, 09:04 - ',
 '07/05/2026, 09:04 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:05 - ',
 '07/05/2026, 09:06 - ',
 '07/05/2026, 09:06 - ',
 '07/05/2026, 09:06 - ',
 '07/05/2026, 09:06 - ',
 '07/05/2026, 09:06 - ',
 '07/05/2026, 09:06 - ',
 '07/05/2026, 09:06 - ',
 '07/05/2026, 09:07 - ',
 '07/05/2026, 09:07 - ',
 '07/05/2026, 09:07 - ',
 '07/05/2026, 09:08 - ',
 '07/05/2026, 09:08 - ',
 '07/05/2026, 09:08 - ',
 '07/05/2026, 09:11 - ',
 '07/05/2026, 09:11 - ',
 '07/05/2026, 09:13 - ',
 '07/05/2026, 09:13 - ',
 '07/05/2026, 09:13 - ',
 '07/05/2026, 09:13 - ',
 '07/05/2026, 09:13 - ',
 '07/05/2026, 09:15 - ',
 '07/05/2026, 09:17 - ',
 '07/05/2026, 09:19 - ',
 '07/05/2026, 09:21 - ',
 '07/05/2026, 09:21 - ',
 '07/05/2026, 09:21 - ',
 '07/05/2026, 09:21 - ',
 '07/05/2026, 09:21 - ',
 '07/05/2026, 09:21 - ',
 '07/05/2026, 09:21 - ',
 '07/05/2026, 09:22 - ',
 '07/05/2026, 09:22 - ',
 '07/05/2026, 09:25 - ',
 '07/05/2026, 09:26 - ',
 '07/05/2026, 09:27 - ',
 '07/05/2026, 09:27 - ',
 '07/05/2026, 09:27 - ',
 '07/05/2026, 09:27 - ',
 '07/05/2026, 09:28 - ',
 '07/05/2026, 09:29 - ',
 '07/05/2026, 09:29 - ',
 '07/05/2026, 09:29 - ',
 '07/05/2026, 09:30 - ',
 '07/05/2026, 09:32 - ',
 '07/05/2026, 09:34 - ',
 '07/05/2026, 09:36 - ',
 '07/05/2026, 09:38 - ',
 '07/05/2026, 09:52 - ',
 '07/05/2026, 09:55 - ',
 '07/05/2026, 10:04 - ',
 '07/05/2026, 10:04 - ',
 '07/05/2026, 10:05 - ',
 '07/05/2026, 10:06 - ',
 '07/05/2026, 10:09 - ',
 '07/05/2026, 10:16 - ',
 '07/05/2026, 10:22 - ',
 '07/05/2026, 10:22 - ',
 '07/05/2026, 10:31 - ',
 '10/05/2026, 14:18 - ',
 '10/05/2026, 20:30 - ',
 '11/05/2026, 22:48 - ',
 '11/05/2026, 22:50 - ',
 '11/05/2026, 22:51 - ',
 '11/05/2026, 22:51 - ',
 '11/05/2026, 22:51 - ',
 '11/05/2026, 22:51 - ',
 '11/05/2026, 22:52 - ',
 '11/05/2026, 22:53 - ',
 '11/05/2026, 22:55 - ',
 '11/05/2026, 22:55 - ',
 '11/05/2026, 22:56 - ',
 '11/05/2026, 22:56 - ',
 '11/05/2026, 22:58 - ',
 '11/05/2026, 22:59 - ',
 '11/05/2026, 23:00 - ',
 '11/05/2026, 23:00 - ',
 '11/05/2026, 23:00 - ',
 '11/05/2026, 23:00 - ',
 '11/05/2026, 23:00 - ',
 '11/05/2026, 23:00 - ',
 '11/05/2026, 23:01 - ',
 '11/05/2026, 23:02 - ',
 '11/05/2026, 23:02 - ',
 '11/05/2026, 23:02 - ',
 '11/05/2026, 23:02 - ',

In [92]:
# Create a DataFrame from the extracted messages
df = pd.DataFrame({'message_date': dates, 'user_message': messages})
df['message_date'] = pd.to_datetime(df['message_date'], format='%d/%m/%Y, %H:%M - ')

In [93]:
df.head()

         message_date                                       user_message
0 2026-05-06 18:25:00  Messages and calls are end-to-end encrypted. O...
1 2026-05-06 18:06:00             Akshat Talwar USAR created group "ㅤ"\n
2 2026-05-06 18:12:00                         Yash ShahiUsar added you\n
3 2026-05-06 18:12:00  Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...
4 2026-05-06 18:12:00  Waqar AkhtarUsar: Agar saath hua toh Geetansh ...

In [94]:
df.shape

(37465, 2)

In [96]:
# seperating user and message
users = []
messages = []
for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s',message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])
df['user'] = users
df['message'] = messages
df.drop(columns=['message'], inplace=True)
df.head(20)

,message_date,user_message,user
0,2026-05-06 18:25:00,Messages and calls are end-to-end encrypted. O...,group_notification
1,2026-05-06 18:06:00,"Akshat Talwar USAR created group ""ㅤ""\n",group_notification
2,2026-05-06 18:12:00,Yash ShahiUsar added you\n,group_notification
3,2026-05-06 18:12:00,Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...,Waqar AkhtarUsar
4,2026-05-06 18:12:00,Waqar AkhtarUsar: Agar saath hua toh Geetansh ...,Waqar AkhtarUsar
5,2026-05-06 18:12:00,Yash ShahiUsar: Saath h\n,Yash ShahiUsar
6,2026-05-06 18:12:00,Yash ShahiUsar: Phir jiya bhi h\n,Yash ShahiUsar
7,2026-05-06 18:14:00,Akshat Talwar USAR: sir ka number hai?\n,Akshat Talwar USAR
8,2026-05-06 18:14:00,Himanshu USAR: +91 75032 88678\n,Himanshu USAR
9,2026-05-06 18:39:00,Yash ShahiUsar: Sir se bhi baat huyi khrhe hos...,Yash ShahiUsar
10,2026-05-06 18:39:00,Yash ShahiUsar: 🙏🏻\n,Yash ShahiUsar
11,2026-05-06 19:09:00,Ojus MathurUsar: Waah\n,Ojus MathurUsar
12,2026-05-06 19:09:00,Ojus MathurUsar: Ye plan to khtm matlab\n,Ojus MathurUsar
13,2026-05-06 20:09:00,Shashank USAR: Kya Krna hai yrr phir 😔\n,Shashank USAR
14,2026-05-06 20:12:00,Akshat Talwar USAR: <Media omitted>\n,Akshat Talwar USAR
15,2026-05-06 20:18:00,Yash ShahiUsar: Abe chinta mt kro shyd kaha th...,Yash ShahiUsar
16,2026-05-06 20:18:00,Yash ShahiUsar: Stick to our plan\n,Yash ShahiUsar
17,2026-05-06 20:19:00,Akshat Talwar USAR: APES TOGETHER STRONG\n,Akshat Talwar USAR
18,2026-05-06 20:19:00,Akshat Talwar USAR: hamare group ka naam leak ...,Akshat Talwar USAR
19,2026-05-06 20:20:00,"Shashank USAR: ""Sir yeh ____ ke bndo ne nakal ...",Shashank USAR

In [97]:
# extracting the dates from the chat data
df['year'] = df['message_date'].dt.year

In [98]:
df.head()

,message_date,user_message,user,year
0,2026-05-06 18:25:00,Messages and calls are end-to-end encrypted. O...,group_notification,2026
1,2026-05-06 18:06:00,"Akshat Talwar USAR created group ""ㅤ""\n",group_notification,2026
2,2026-05-06 18:12:00,Yash ShahiUsar added you\n,group_notification,2026
3,2026-05-06 18:12:00,Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...,Waqar AkhtarUsar,2026
4,2026-05-06 18:12:00,Waqar AkhtarUsar: Agar saath hua toh Geetansh ...,Waqar AkhtarUsar,2026

In [99]:
# extracting month name
df['month_num'] = df['message_date'].dt.month_name()

In [100]:
df.head()

,message_date,user_message,user,year,month_num
0,2026-05-06 18:25:00,Messages and calls are end-to-end encrypted. O...,group_notification,2026,May
1,2026-05-06 18:06:00,"Akshat Talwar USAR created group ""ㅤ""\n",group_notification,2026,May
2,2026-05-06 18:12:00,Yash ShahiUsar added you\n,group_notification,2026,May
3,2026-05-06 18:12:00,Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...,Waqar AkhtarUsar,2026,May
4,2026-05-06 18:12:00,Waqar AkhtarUsar: Agar saath hua toh Geetansh ...,Waqar AkhtarUsar,2026,May

In [101]:
# extracting dates from the chat data
df['day'] = df['message_date'].dt.day

In [102]:
df.head()

,message_date,user_message,user,year,month_num,day
0,2026-05-06 18:25:00,Messages and calls are end-to-end encrypted. O...,group_notification,2026,May,6
1,2026-05-06 18:06:00,"Akshat Talwar USAR created group ""ㅤ""\n",group_notification,2026,May,6
2,2026-05-06 18:12:00,Yash ShahiUsar added you\n,group_notification,2026,May,6
3,2026-05-06 18:12:00,Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...,Waqar AkhtarUsar,2026,May,6
4,2026-05-06 18:12:00,Waqar AkhtarUsar: Agar saath hua toh Geetansh ...,Waqar AkhtarUsar,2026,May,6

In [103]:
# extracting hours
df['hour'] = df['message_date'].dt.hour

In [104]:
df.head()  # Display the first few rows of the DataFrame to verify the structure

,message_date,user_message,user,year,month_num,day,hour
0,2026-05-06 18:25:00,Messages and calls are end-to-end encrypted. O...,group_notification,2026,May,6,18
1,2026-05-06 18:06:00,"Akshat Talwar USAR created group ""ㅤ""\n",group_notification,2026,May,6,18
2,2026-05-06 18:12:00,Yash ShahiUsar added you\n,group_notification,2026,May,6,18
3,2026-05-06 18:12:00,Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...,Waqar AkhtarUsar,2026,May,6,18
4,2026-05-06 18:12:00,Waqar AkhtarUsar: Agar saath hua toh Geetansh ...,Waqar AkhtarUsar,2026,May,6,18

In [105]:
#extracting minutes
df['minute'] = df['message_date'].dt.minute

In [106]:
df.head()  # Display the first few rows of the DataFrame to verify the structure

,message_date,user_message,user,year,month_num,day,hour,minute
0,2026-05-06 18:25:00,Messages and calls are end-to-end encrypted. O...,group_notification,2026,May,6,18,25
1,2026-05-06 18:06:00,"Akshat Talwar USAR created group ""ㅤ""\n",group_notification,2026,May,6,18,6
2,2026-05-06 18:12:00,Yash ShahiUsar added you\n,group_notification,2026,May,6,18,12
3,2026-05-06 18:12:00,Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...,Waqar AkhtarUsar,2026,May,6,18,12
4,2026-05-06 18:12:00,Waqar AkhtarUsar: Agar saath hua toh Geetansh ...,Waqar AkhtarUsar,2026,May,6,18,12

In [107]:
# removing message_date column as we have extracted all the information from it
df.drop(columns=['message_date'], inplace=True)

In [109]:
df.head()  # Display the first few rows of the DataFrame to verify the structure

,user_message,user,year,month_num,day,hour,minute
0,Messages and calls are end-to-end encrypted. O...,group_notification,2026,May,6,18,25
1,"Akshat Talwar USAR created group ""ㅤ""\n",group_notification,2026,May,6,18,6
2,Yash ShahiUsar added you\n,group_notification,2026,May,6,18,12
3,Waqar AkhtarUsar: Ek baar pta kar ki B2 ka kab...,Waqar AkhtarUsar,2026,May,6,18,12
4,Waqar AkhtarUsar: Agar saath hua toh Geetansh ...,Waqar AkhtarUsar,2026,May,6,18,12